services:
  db:
    image: postgres
    container_name: migsbyu_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prod
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - migsbyu_network
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: migsbyu_api
    restart: "unless-stopped"
    depends_on:
      - db
    networks:
      - migsbyu_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    image: migsbyu_frontend
    restart: "unless-stopped"
    depends_on:
      - db
      - api
    networks:
      - migsbyu_network

networks:
  migsbyu_network:
    driver: bridge
    name: migsbyu_network
